fix: don't import VPC VRFs when there aren't any VPCs (#1023)
## Description

Small bug fix!
https://github.com/NVIDIA/ncx-infra-controller-core/pull/649 introduced
some new config options to allow default-route leak support.

### The Problem

The problem is there are a couple of spots that drop a `list:` block
with the expectation there are `tenant.Vpcs` to iterate over (to list
VRFs to import), but when there are no VPCs, you end up with an empty
`list:` that looks like this:

```
                route-import:
                  from-vrf:
                    route-map: leak_to_underlay
                    enable: on
                    list: <-- the problem
              ipv6-unicast:
```

...which breaks the YAML parser, and we get an error, which shows up in
logs:

```
level=ERROR msg="update_nvue post command failed: cmd 'ip vrf exec mgmt
crictl exec <hbn-container-id> nv config replace
/var/support/nvue_startup.yaml' failed with status: exit status: 1, stderr:
Error: 'set' operation values must not be 'null'.
execing command in container <hbn-container-id>: command terminated with
exit code 1, stdout: " location="crates/agent/src/nvue.rs:754"
level=ERROR msg="Writing network configuration" error="..."
location="crates/agent/src/main_loop.rs:801"
```

### The Fix

The fix is to wrap the entire `route-import:` block in an `{{- if
$tenant.Vpcs }} ... {{- end}}`. When there are no tenant VPCs, the
import section is omitted.

Verified this by actually modifying + reloading the config on one of the
broken DPUs to make sure the fix was the fix.

I had *also* tried to just block off the `from-vrf:` section, but that
leaves you with an empty `route-import:` block, and puts you back in the
same spot. The fix is to just drop the entire `route-import` block that
we're adding entirely (which was the thing added in the original PR).

..and then once the DPU is fed VPCs, the agent will fill it all back
out.

Also added a test + generic test helper while I'm in here!

Signed-off-by: Chet Nichols III <chetn@nvidia.com>

## Type of Change
<!-- Check one that best describes this PR -->
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality  
- [x] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Related Issues (Optional)
<!-- If applicable, provide GitHub Issue. -->

## Breaking Changes
- [ ] This PR contains breaking changes

<!-- If checked above, describe the breaking changes and migration steps
-->

## Testing
<!-- How was this tested? Check all that apply -->
- [x] Unit tests added/updated
- [ ] Integration tests added/updated  
- [ ] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes
<!-- Any additional context, deployment notes, or reviewer guidance -->

Signed-off-by: Chet Nichols III <chetn@nvidia.com>